### ISSUE TITLE
Race condition / synchronization bug in doCommand.ab

### ISSUE THREAD

**Issue by klauer** [epics-motor/motorAerotech#2]
doCommand accesses `IGLOBAL` multiple times in the same loop, which allows commands to be acknowledged but never actually interpreted. For example, imagine if `IGLOBAL(cmdVar)` is set by EPICS right before the Aerotech controller interprets the line `IGLOBAL(cmdVar) = -(IGLOBAL(cmdVar))`: the entire `IF` block will never even see it on the next iteration.

I've had this fixed for a long while for use at SLAC (and regret not having proposed this upstream before the project split off...) just by stashing the command at the beginning of the loop and working with it:
https://github.com/klauer/motor/commit/a1a21ff83768f9605fa181afe9c329f17ec68a04

**Comment by kmpeters** [comment]
@klauer, thanks for this.  

@timmmooney, I wonder if this proposed change might eliminate the need for the Write*AndCheck functions in EnsembleTrajectoryScan.st.  Thoughts?

**Comment by timmmooney** [comment]
Awesome!  It might very well eliminate the need for Write*AndCheck.  That would be beautiful.
